version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - aws s3 cp s3://modusbox-build-cache/settings.xml /root/.m2/settings.xml
      - mvn deploy -U -Djgitver.session=true -Djgitver.branch=$(git branch -a --points-at $CODEBUILD_RESOLVED_SOURCE_VERSION | sed -n 2p | awk '{ printf $1 }')

cache:
  paths:
    - '/root/.m2/**/*'